runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

#[START env]
env_variables:
  DATASET_ID: yafet_test
  TABLE_ID: realtime_markedmondsonme
  SECRET_SALT: blahblahblah
#[END env]
